#!/bin/sh
# by:   bitacorabyte
# date: 20241207
# Entorno de desarrollo: debian 12 (bookworm)
# Basado en la documentación oficial: https://docs.librenms.org/Installation/Install-LibreNMS/#prepare-linux-server
##
# Este script realiza las siguientes tareas:
# 1. Actualiza el sistema
# 2. Variables
# 3. Instalar depedencias
# 4. Instalar Nginx
# 5. Instalar PHP
# 6. Instalar MariaDB
# 7. Añadir al usuario de LibreNMS
# 8. Descargar LibreNMS
# 9. Establecer permisos
# 10. Instalar dependencias de PHP
# 11. Establecer el timezone
# 12. Configurar MariaDB
# 13. Configurar PHP-FPM
# 14. Configurar Web Server
# 15. Habilitar comandos lnms
# 16. Configurar snmpd
# 17. Configurar cron
# 18. Habilittar el horario
# 19. Configurar logrotate
##

# 1. Actualizar SO
echo "***1. Actualizando el sistema"
apt update && apt upgrade -y

# 2. Variables
echo "***2. Declarando las variables"
TIMEZONE = "Europe/Madrid"
echo -n "Password para el root de la BD: "
read -r DB_ROOT_PSW
echo -n "Usuario de BD para LibreNMS: "
echo -r DB_USER
echo -n "Password de BD para el usuario de LibreNMS: "
echo -r DB_PSW
echo -n "Nombre para la BD: "
echo -r DB_NAME
echo -n "Usuario de LibreNMS"
echo -r LNMS_USER

# 3 Instalar dependencias
echo "***3 .Instalando dependencias."
apt install -y apt-transport-https lsb-release ca-certificates wget acl curl fping git graphviz imagemagick mtr-tiny nmap python3-dotenv python3-pymysql python3-redis python3-setuptools python3-systemd python3-pip rrdtool snmp snmpd unzip whois

# 4 Instalar nginx
echo "***4. Instalando nginx"
apt install -y nginx-full

# 5 Instalar PHP
echo "***5. Instalando PHP"
apt install -y php-cli php-curl php-fpm php-gd php-gmp php-mbstring php-mysql php-snmp php-xml php-zip

# 6. Instalar MariaDB
echo "***6. Instalando MariaDB"
apt install -y mariadb-client mariadb-server

# 7. Añadir al usuario de LibreNMS
echo "***7. Añadiendo al usuario de LibreNMS"
useradd $LNMS_USER -d /opt/librenms -M -r -s "$(which bash)"

# 8. Descargar LibreNMS
echo "***8. Descargando LibreNMS"
cd /opt
git clone https://github.com/librenms/librenms.git

# 9. Establecer permisos
echo "***9. Estableciendo permisos al usuario en las carpetas de la app"
chown -R $LNMS_USER:$LNMS_USER /opt/librenms
chmod 771 /opt/librenms
setfacl -d -m g::rwx /opt/librenms/rrd /opt/librenms/logs /opt/librenms/bootstrap/cache/ /opt/librenms/storage/
setfacl -R -m g::rwx /opt/librenms/rrd /opt/librenms/logs /opt/librenms/bootstrap/cache/ /opt/librenms/storage/

# 10. Instalar dependencias de PHP
echo "***10. Resolviendo dependencias de PHP"
su - $LNMS_USER
./scripts/composer_wrapper.php install --no-dev
exit

# 11. Establecer timezona
echo "***1. Estableciendo timezone del sistema y php.ini"
timedatectl set-timezone "$TIMEZONE"
# Buscar el archivo php.ini (ajusta la ruta según tu sistema)
php_ini_dir=$(php --ini | grep 'Loaded Configuration' | sed 's|.* => ||')
php_ini_file=$(find "$php_ini_dir" -name php.ini -print -quit)
# Configurar la zona horaria en php.ini
sed -i "s/date.timezone = .*/date.timezone = $TIME_ZONE/" "$php_ini_file"

# 12. Configurar MariaDB
echo "***12. Configurando MariaDB"
sudo sed -i '$ a\innodb_file_per_table=1' /etc/mysql/mariadb.conf.d/50-server.cnf
sudo sed -i '$ a\lower_case_table_names=0' /etc/mysql/mariadb.conf.d/50-server.cnf
systemctl enable mariadb
systemctl start mariadb
mysql -e "CREATE DATABASE ${DB_NAME} CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;"
mysql -e "CREATE USER '${DB_USER}'@'localhost' IDENTIFIED BY '${DB_PSW}';"
mysql -e "GRANT ALL PRIVILEGES ON ${DB_NAME}.* TO '${DB_USER}'@'localhost';"

# 13. Configurar PHP-FPM
echo "***13. Configurando php-fpm"
cp /etc/php/8.2/fpm/pool.d/www.conf /etc/php/8.2/fpm/pool.d/librenms.conf
sed -i 's/\[www\]/\[librenms\]/g' /etc/php/8.2/fpm/pool.d/librenms.conf
sed -i "s/user = .*/user = $LMNS_USER/g" /etc/php/8.2/fpm/pool.d/librenms.conf
sed -i "s/group = .*/group = $LMNS_USER/g" /etc/php/8.2/fpm/pool.d/librenms.conf
sed -i 's/listen = .*/listen = \/run\/php-fpm-librenms\.sock/g' /etc/php/8.2/fpm/pool.d/librenms.conf

# 14. Configurar Web Server
echo "***14. Configurando el Web Server"
CONFIG="
server {
    listen      80;
    server_name librenms.bitacorabyte.local;
    root        /opt/librenms/html;
    index       index.php;
    charset     utf-8;
    gzip        on;
    gzip_types  text/css application/javascript text/javascript application/x-javascript image/svg+xml text/plain text/xsd text/xsl text/xml image/x-icon;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ [^/]\.php(/|$) {
        fastcgi_pass unix:/run/php-fpm-librenms.sock;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        include fastcgi.conf;
    }

    location ~ /\.(?!well-known).* {
        deny all;
    }
}
"
echo "$CONFIG" >> /etc/nginx/sites-enabled/librenms.vhost
sudo nginx -t

if [ $? -eq 0 ]; then
  echo "Configuration added successfully. Reloading Nginx..."
  rm /etc/nginx/sites-enabled/default
  systemctl reload nginx
  systemctl restart php8.2-fpm
else
  echo "Error in configuration. Please check the syntax and try again."
fi

# 15. Habilitar comandos lmns
echo "***15. Habilitando los comandos de lmns"
ln -s /opt/librenms/lnms /usr/bin/lnms
cp /opt/librenms/misc/lnms-completion.bash /etc/bash_completion.d/

#16. Configurar snmpd
echo "***16. Configurando snmpd"
cp /opt/librenms/snmpd.conf.example /etc/snmp/snmpd.conf
sed -i "s/RANDOMSTRINGGOESHERE/public/g" /etc/snmp/snmpd.conf
curl -o /usr/bin/distro https://raw.githubusercontent.com/librenms/librenms-agent/master/snmp/distro
chmod +x /usr/bin/distro
systemctl enable snmpd
systemctl restart snmpd

# 17. Configurar cron
echo "***17. Configurando cron"
cp /opt/librenms/dist/librenms.cron /etc/cron.d/librenms

# 18. Habilittar el horario
echo "***18. Habilitando el horario"
cp /opt/librenms/dist/librenms-scheduler.service /opt/librenms/dist/librenms-scheduler.timer /etc/systemd/system/
systemctl enable librenms-scheduler.timer
systemctl start librenms-scheduler.timer

# 19. Configurar logrotate
cp /opt/librenms/misc/librenms.logrotate /etc/logrotate.d/librenms
